
name: lab10-workflow-stepcd
on: workflow_dispatch
jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: qemu
        uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
      - id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: kamil4/zad2gitops:v1
          cache-from: type=registry,ref=kamil4/zad2gitops:v1
          cache-to: type=inline
